/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUserRouteImport } from './routes/api.user'
import { Route as ApiListingsRouteImport } from './routes/api.listings'
import { Route as ApiGamesRouteImport } from './routes/api.games'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsRoute = ApiListingsRouteImport.update({
  id: '/api/listings',
  path: '/api/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesRoute = ApiGamesRouteImport.update({
  id: '/api/games',
  path: '/api/games',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/games': typeof ApiGamesRoute
  '/api/listings': typeof ApiListingsRoute
  '/api/user': typeof ApiUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/games': typeof ApiGamesRoute
  '/api/listings': typeof ApiListingsRoute
  '/api/user': typeof ApiUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/games': typeof ApiGamesRoute
  '/api/listings': typeof ApiListingsRoute
  '/api/user': typeof ApiUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/games' | '/api/listings' | '/api/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/games' | '/api/listings' | '/api/user'
  id: '__root__' | '/' | '/api/games' | '/api/listings' | '/api/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGamesRoute: typeof ApiGamesRoute
  ApiListingsRoute: typeof ApiListingsRoute
  ApiUserRoute: typeof ApiUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings': {
      id: '/api/listings'
      path: '/api/listings'
      fullPath: '/api/listings'
      preLoaderRoute: typeof ApiListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games': {
      id: '/api/games'
      path: '/api/games'
      fullPath: '/api/games'
      preLoaderRoute: typeof ApiGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGamesRoute: ApiGamesRoute,
  ApiListingsRoute: ApiListingsRoute,
  ApiUserRoute: ApiUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
